name: Dispatch central Planuze pack scan

on:
  workflow_dispatch:

permissions: {}

jobs:
  scan:
    permissions:
      id-token: write
    uses: Planuze-Software/pack-scan-runner/.github/workflows/pack-scan-central.yml@c2229e3d02adf1118a40fe61e85c9a9507546aa0
